
const goldMembers = [
	{ name: '3 Banken IT', logo: '3bankenit.png', poster: '3Bankenit.jpg'},
	{ name: 'Alpine Metal Tech GmbH', logo: 'alpine-metal-tech.png', poster: ''},
	{ name: 'Avocodo GmbH' , logo: 'avocodo.png', poster: '' },
	{ name: 'BARMHERZIGE BRÜDER Krankenhaus Linz', logo: 'barmherzige-brueder.png', poster: '' },
	{ name: 'BMD Systemhaus', logo: 'bmd_business_software.png', poster: 'BMD.jpg' },
	{ name: 'CBCX Technologies GmbH', logo: 'cbcx.png', poster: '' },
	{ name: 'CGM Clinical Österreich GmbH', logo: 'cgm.webp', poster: '' },
	{ name: 'clickandlearn GmbH', logo: 'clickandlearn.png', poster: '' },
	{ name: 'client4u IT-Consulting GmbH', logo: 'client4u.png', poster: '' },
	{ name: 'Cloudflight Austria GmbH', logo: 'cloudflight.png', poster: '' },
	{ name: 'COUNT IT GmbH', logo: 'count-it.png', poster: '' },
	{ name: 'Ebner Media & Management GmbH', logo: 'ebner-media.png', poster: '' },
	{ name: 'Eisenbeiss GmbH', logo: 'eisenbeiss.png', poster: '' },
	{ name: 'ENGEL AUSTRIA GmbH', logo: 'engel.jpg', poster: 'engel.jpg' },
	{ name: 'epunkt GmbH', logo: 'epunkt.png', poster: '' },
	{ name: 'FH OÖ Hagenberg, IT GmbH', logo: 'fhooe.png', poster: 'fhooe.jpg' },
	{ name: 'Herbsthofer GmbH', logo: 'herbsthofer.png', poster: '' },
	{ name: 'HÖDLMAYR INTERNATIONAL AG', logo: 'hoedlmayr.png', poster: 'hoedlmayr.png' },
	{ name: 'IBM ix Austria GmbH', logo: 'ibm-ix.png', poster: '' },
	{ name: 'IGS Systemmanagement GmbH & CO KG', logo: 'isglogo.png', poster: '' },
	{ name: 'KEBA Group AG', logo: 'keba.png', poster: '' },
	{ name: 'KE KELIT', logo: 'kekelit.png', poster: 'kekelit.jpg' },
	{ name: 'Latschbacher GmbH - WinforstPro', logo: 'latschbacher-winforstpro.jpg', poster: '' },
	{ name: 'Miba AG', logo: 'miba.png', poster: '' },
	{ name: 'mobile agreements GmbH', logo: 'mo_gree.png', poster: '' },
	{ name: 'Netural GmbH', logo: 'netural.png', poster: '' },
	{ name: 'ÖGK, IKT OÖ', logo: 'ikt.png', poster: '' },
	{ name: 'PROGRAMMIERFABRIK GmbH', logo: 'programmierfabrik.png', poster: '' },
	{ name: 'Raiffeisenlandesbank OÖ Aktiengesellschaft', logo: 'raiffeisen.png', poster: 'raitec.jpg' },
	{ name: 'solvistas GmbH', logo: 'solvistas.png', poster: 'solvistas.jpg' },
	{ name: 'Sprecher Automation GmbH', logo: 'sprecher-automation.png', poster: '' },
	{ name: 'STIWA Holding GmbH', logo: 'stiwa.png', poster: '' },
	{ name: 'TeamViewer Austria GmbH', logo: 'teamviewer.png', poster: '' },
	{ name: 'technosert electronic GmbH', logo: 'technosert.png', poster: '' },
	{ name: 'TRAUNER Verlag + Buchservice GmbH', logo: 'trauner.png', poster: '' },
	{ name: 'TRUMPF Maschinen Austria GmbH + Co. KG', logo: 'trumpf.png', poster: '' },
	{ name: 'Uni Software Plus GmbH', logo: 'unisoftwareplus.png', poster: '' },
	{ name: 'Wacker Neuson Linz GmbH', logo: 'wacker-neuson.png', poster: '' },
	{ name: 'Wirtschaftskammer Oberösterreich', logo: 'wkooe.png', poster: 'wkooe.jpg' }
  ]
  