
const goldMembers = [
	{ name: 'Alpine Metal Tech GmbH', logo: 'alpine-metal-tech.png' },
	{ name: 'Avocodo GmbH' , logo: 'avocodo.png' },
	{ name: 'BARMHERZIGE BRÜDER Krankenhaus Linz', logo: 'barmherzige-brueder.png' },
	{ name: 'BMD Systemhaus', logo: 'bmd_business_software.png' },
	{ name: 'CBCX Technologies GmbH', logo: 'cbcx.png' },
	{ name: 'CGM Clinical Österreich GmbH', logo: 'cgm.webp' },
	{ name: 'clickandlearn GmbH', logo: 'clickandlearn.png' },
	{ name: 'client4u IT-Consulting GmbH', logo: 'client4u.png' },
	{ name: 'Cloudflight Austria GmbH', logo: 'cloudflight.png' },
	{ name: 'COUNT IT GmbH', logo: 'count-it.png' },
	{ name: 'Ebner Media & Management GmbH', logo: 'ebner-media.png' },
	{ name: 'Eisenbeiss GmbH', logo: 'eisenbeiss.png' },
	{ name: 'ENGEL AUSTRIA GmbH', logo: 'engel.jpg' },
	{ name: 'epunkt GmbH', logo: 'epunkt.png' },
	{ name: 'FH OÖ Hagenberg, IT GmbH', logo: 'fhooe.png' },
	{ name: 'Herbsthofer GmbH', logo: 'herbsthofer.png' },
	{ name: 'HÖDLMAYR INTERNATIONAL AG', logo: 'hoedlmayr.png' },
	{ name: 'IBM ix Austria GmbH', logo: 'ibm-ix.png' },
	{ name: 'IGS Systemmanagement GmbH & CO KG', logo: 'isglogo.png' },
	{ name: 'KEBA Group AG', logo: 'keba.png' },
	{ name: 'Latschbacher GmbH - WinforstPro', logo: 'latschbacher-winforstpro.jpg' },
	{ name: 'Miba AG', logo: 'miba.png' },
	{ name: 'mobile agreements GmbH', logo: 'mo_gree.png' },
	{ name: 'Netural GmbH', logo: 'netural.png' },
	{ name: 'ÖGK, IKT OÖ', logo: 'ikt.png' },
	{ name: 'PROGRAMMIERFABRIK GmbH', logo: 'programmierfabrik.png' },
	{ name: 'Raiffeisenlandesbank OÖ Aktiengesellschaft', logo: 'raiffeisen.png' },
	{ name: 'solvistas GmbH', logo: 'solvistas.png' },
	{ name: 'Sprecher Automation GmbH', logo: 'sprecher-automation.png' },
	{ name: 'STIWA Holding GmbH', logo: 'stiwa.png' },
	{ name: 'TeamViewer Austria GmbH', logo: 'teamviewer.png' },
	{ name: 'technosert electronic GmbH', logo: 'technosert.png' },
	{ name: 'TRAUNER Verlag + Buchservice GmbH', logo: 'trauner.png' },
	{ name: 'TRUMPF Maschinen Austria GmbH + Co. KG', logo: 'trumpf.png' },
	{ name: 'Uni Software Plus GmbH', logo: 'unisoftwareplus.png' },
	{ name: 'Wacker Neuson Linz GmbH', logo: 'wacker-neuson.png' },
	{ name: 'Wirtschaftskammer Oberösterreich', logo: 'wkooe.png' }
  ]
  