
const goldMembers = [
	{ name: 'Alpine Metal Tech GmbH' },
	{ name: 'Avocodo GmbH' },
	{ name: 'BARMHERZIGE BRÜDER Krankenhaus Linz' },
	{ name: 'BMD Systemhaus' },
	{ name: 'CBCX Technologies GmbH' },
	{ name: 'CGM Clinical Österreich GmbH' },
	{ name: 'clickandlearn GmbH' },
	{ name: 'client4u IT-Consulting GmbH' },
	{ name: 'Cloudflight Austria GmbH' },
	{ name: 'COUNT IT GmbH' },
	{ name: 'Ebner Media & Management GmbH' },
	{ name: 'Eisenbeiss GmbH' },
	{ name: 'ENGEL AUSTRIA GmbH' },
	{ name: 'epunkt GmbH' },
	{ name: 'FH OÖ IT GmbH' },
	{ name: 'FH OÖ Hagenberg' },
	{ name: 'Herbsthofer GmbH' },
	{ name: 'HÖDLMAYR INTERNATIONAL AG' },
	{ name: 'IBM ix Austria GmbH' },
	{ name: 'IGS Systemmanagement GmbH & CO KG' },
	{ name: 'KEBA Group AG' },
	{ name: 'Latschbacher GmbH - WinforstPro' },
	{ name: 'Miba AG' },
	{ name: 'mobile agreements GmbH' },
	{ name: 'Netural GmbH' },
	{ name: 'ÖGK, IKT OÖ' },
	{ name: 'PROGRAMMIERFABRIK GmbH' },
	{ name: 'Raiffeisenlandesbank OÖ Aktiengesellschaft' },
	{ name: 'solvistas GmbH' },
	{ name: 'Sprecher Automation GmbH' },
	{ name: 'STIWA Holding GmbH' },
	{ name: 'TeamViewer Austria GmbH' },
	{ name: 'technosert electronic GmbH' },
	{ name: 'TRAUNER Verlag + Buchservice GmbH' },
	{ name: 'TRUMPF Maschinen Austria GmbH + Co. KG' },
	{ name: 'Uni Software Plus GmbH' },
	{ name: 'Wacker Neuson Linz GmbH' },
	{ name: 'Wirtschaftskammer Oberösterreich' }
  ]
  