
const goldMembers = [
	{ name: '3 Banken IT GmbH' },
	{ name: 'AGILOX Services GmbH' },
	{ name: 'Alpine Metal Tech GmbH' },
	{ name: 'Avocodo GmbH' },
	{ name: 'Barmherzige Brüder Krankenhaus Linz' },
	{ name: 'BMD Systemhaus' },
	{ name: 'CBCX Technologies GmbH' },
	{ name: 'CGM Clinical Österreich GmbH' },
	{ name: 'clickandlearn GmbH' },
	{ name: 'Cloudflight Austria GmbH' },
	{ name: 'coilDNA' },
	{ name: 'COUNT IT GmbH' },
	{ name: 'EBM GmbH' },
	{ name: 'Ebner Media & Management GmbH' },
	{ name: 'EFINIO GmbH' },
	{ name: 'Eisenbeiss GmbH' },
	{ name: 'ELO Digital Office AT GmbH' },
	{ name: 'ENGEL AUSTRIA GmbH' },
	{ name: 'epunkt GmbH' },
	{ name: 'Fabasoft International Services GmbH' },
	{ name: 'FAW Solutions GmbH' },
	{ name: 'FERCHAU Austria GmbH' },
	{ name: 'FH OÖ IT GmbH' },
	{ name: 'FH OÖ Hagenberg Hardware-Software-Design' },
	{ name: 'Herbsthofer GmbH' },
	{ name: 'HÖDLMAYR INTERNATIONAL AG' },
	{ name: 'IBM ix Austria GmbH' },
	{ name: 'IGS Systemmanagement GmbH & CO KG' },
	{ name: 'ITPRO Consulting & Software GmbH' },
	{ name: 'KE KELIT GmbH' },
	{ name: 'KEBA Group AG' },
	{ name: 'KREISEL Electric GmbH' },
	{ name: 'Latschbacher GmbH - WinforstPro' },
	{ name: 'Linz AG' },
	{ name: 'Miba AG' },
	{ name: 'MIC Datenverarbeitung GmbH' },
	{ name: 'mobile agreements GmbH' },
	{ name: 'Netural GmbH' },
	{ name: 'Nimbuscloud Gmbh' },
	{ name: 'NTS Retail KG' },
	{ name: 'ÖGK IKT OÖ' },
	{ name: 'Primetals Technologies Austria GmbH' },
	{ name: 'PROGRAMMIERFABRIK GmbH' },
	{ name: 'Raiffeisen Software GmbH' },
	{ name: 'Raiffeisenlandesbank Oberösterreich Aktiengesellschaft' },
	{ name: 'RAITEC GmbH' },
	{ name: 'SecureGUARD GmbH' },
	{ name: 'SKE Engineering Gmbh' },
	{ name: 'Softpoint IT-Solutions GmbH & Co KG' },
	{ name: 'solvistas GmbH' },
	{ name: 'Sprecher Automation GmbH' },
	{ name: 'STIWA Holding GmbH' },
	{ name: 'TeamViewer Austria GmbH' },
	{ name: 'TGW Logistics Group' },
	{ name: 'TRAUNER Verlag + Buchservice GmbH' },
	{ name: 'TRUMPF Maschinen Austria GmbH + Co. KG' },
	{ name: 'umdasch Store Makers Management GmbH' },
	{ name: 'Uni Software Plus GmbH' },
	{ name: 'VSTech Service & Engineering GmbH' },
	{ name: 'Wacker Neuson Linz GmbH' },
	{ name: 'Wirtschaftskammer Oberösterreich' }
	
]