
const goldMembers = [
	{ name: '3 Banken IT GmbH', img: '' },
	{ name: 'AGILOX Services GmbH', img: '' },
	{ name: 'Alpine Metal Tech GmbH', img: '' },
	{ name: 'Avocodo GmbH', img: '' },
	{ name: 'Barmherzige Brüder Krankenhaus Linz', img: '' },
	{ name: 'BMD Systemhaus', img: '' },
	{ name: 'CBCX Technologies GmbH', img: '' },
	{ name: 'CGM Clinical Österreich GmbH', img: '' },
	{ name: 'clickandlearn GmbH', img: '' },
	{ name: 'Cloudflight Austria GmbH', img: '' },
	{ name: 'coilDNA', img: '' },
	{ name: 'COUNT IT GmbH', img: '' },
	{ name: 'EBM GmbH', img: '' },
	{ name: 'Ebner Media & Management GmbH', img: '' },
	{ name: 'EFINIO GmbH', img: '' },
	{ name: 'Eisenbeiss GmbH', img: '' },
	{ name: 'ELO Digital Office AT GmbH', img: '' },
	{ name: 'ENGEL AUSTRIA GmbH', img: '' },
	{ name: 'epunkt GmbH', img: '' },
	{ name: 'Fabasoft International Services GmbH', img: '' },
	{ name: 'FAW Solutions GmbH', img: '' },
	{ name: 'FERCHAU Austria GmbH', img: '' },
	{ name: 'FH OÖ IT GmbH', img: '' },
	{ name: 'FH OÖ Hagenberg Hardware-Software-Design', img: '' },
	{ name: 'Herbsthofer GmbH', img: '' },
	{ name: 'HÖDLMAYR INTERNATIONAL AG', img: '' },
	{ name: 'IBM ix Austria GmbH', img: '' },
	{ name: 'IGS Systemmanagement GmbH & CO KG', img: '' },
	{ name: 'ITPRO Consulting & Software GmbH', img: '' },
	{ name: 'KE KELIT GmbH', img: '' },
	{ name: 'KEBA Group AG', img: '' },
	{ name: 'KREISEL Electric GmbH', img: '' },
	{ name: 'Latschbacher GmbH - WinforstPro', img: '' },
	{ name: 'Linz AG', img: '' },
	{ name: 'Miba AG', img: '' },
	{ name: 'MIC Datenverarbeitung GmbH', img: '' },
	{ name: 'mobile agreements GmbH', img: '' },
	{ name: 'Netural GmbH', img: '' },
	{ name: 'Nimbuscloud Gmbh', img: '' },
	{ name: 'NTS Retail KG', img: '' },
	{ name: 'ÖGK IKT OÖ', img: '' },
	{ name: 'Primetals Technologies Austria GmbH', img: '' },
	{ name: 'PROGRAMMIERFABRIK GmbH', img: '' },
	{ name: 'Raiffeisen Software GmbH', img: '' },
	{ name: 'Raiffeisenlandesbank Oberösterreich Aktiengesellschaft', img: '' },
	{ name: 'RAITEC GmbH', img: '' },
	{ name: 'SecureGUARD GmbH', img: '' },
	{ name: 'SKE Engineering Gmbh', img: '' },
	{ name: 'Softpoint IT-Solutions GmbH & Co KG', img: '' },
	{ name: 'solvistas GmbH', img: '' },
	{ name: 'Sprecher Automation GmbH', img: '' },
	{ name: 'STIWA Holding GmbH', img: '' },
	{ name: 'TeamViewer Austria GmbH', img: '' },
	{ name: 'TGW Logistics Group', img: '' },
	{ name: 'TRAUNER Verlag + Buchservice GmbH', img: '' },
	{ name: 'TRUMPF Maschinen Austria GmbH + Co. KG', img: '' },
	{ name: 'umdasch Store Makers Management GmbH', img: '' },
	{ name: 'Uni Software Plus GmbH', img: '' },
	{ name: 'VSTech Service & Engineering GmbH', img: '' },
	{ name: 'Wacker Neuson Linz GmbH', img: '' },
	{ name: 'Wirtschaftskammer Oberösterreich', img: '' }
	
]